### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by faustM** [HatimDev-HE/Portfolio-site#5]
Hi [@HatimDev-HE ] 👋,
Your project is complete! There is nothing else to say other than... it's time to merge it :ship: :

Congratulations! 🎉 🎉 🎉 🎉 🎉
Cheers and Happy coding!👏👏👏

**Comment by Lasten-Ernest** [comment]
Good work! Your code looks professional. 

- Well documented README file.
- No linter errors
- No unnecessary line space.
- Good indentation.
- Meaningful html tags.

**Comment by Suzi216** [comment]
SUGGESTION

The code looks good until now.
A small suggestion would be to structure the html element so they could take fewer lines.
